### ISSUE TITLE
Fix NP Atlas fungal filter

### ISSUE THREAD

**Issue by jvansan** [liningtonlab/snapms#3]
JJ vdHooft reported error on submitted but w/ Atlas Fungi Filter

**Comment by rlinington** [comment]
I confirm that this bug is correct. Using these masses from pochonins A- E with full Atlas you get the right answer. With fungi only the job fails.

367.0943
383.0892
401.0553
351.0994
367.0943

**Comment by rlinington** [comment]
These masses are the [M+H]+ in all cases. 

We should review the bacterial and custom filters as well to make sure they don't have the same issue.

**Comment by jvansan** [comment]
Fixed in [releases/v1.2.1](https://github.com/liningtonlab/snapms/releases/tag/v1.2.1) and deployed to np atlas.
